### ISSUE TITLE
TS2307: Cannot find module '../config/WebappConfiguration'

### ISSUE THREAD

**Issue by yairchu** [projectit-org/ProjectIt#282]
On current HEAD 80163e2d933f2f6b4a1c89e08d1e1478fe9abd99, following the README instructions,
when doing the step of

    cd packages/playground
    yarn dev

I get the following error:

```
% yarn dev
yarn run v1.22.15
$ cross-env NODE_PORT=3002 rollup -c -w
rollup v2.77.0
bundles src/webapp/main.ts → public/build/bundle.js...
(!) Plugin typescript: @rollup/plugin-typescript TS2307: Cannot find module '../config/WebappConfiguration' or its corresponding type declarations.
src/webapp/language/EditorRequestsHandler.ts: (1:35)

1 import { editorEnvironment } from "../config/WebappConfiguration";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/webapp/language/EditorState.ts: (22:56)

22 import { editorEnvironment, serverCommunication } from "../config/WebappConfiguration";
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/webapp/language/ImportExportHandler.ts: (3:56)

3 import { editorEnvironment, serverCommunication } from "../config/WebappConfiguration";
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/webapp/language/LanguageInitializer.ts: (8:35)

8 import { editorEnvironment } from "../config/WebappConfiguration";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[!] Error: Could not resolve './config/WebappConfiguration' from src/webapp/FreonLayout.svelte
Error: Could not resolve './config/WebappConfiguration' from src/webapp/FreonLayout.svelte
    at error (/Users/yairchu/dev/src/ProjectIt/packages/playground/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/Users/yairchu/dev/src/ProjectIt/packages/playground/node_modules/rollup/dist/shared/rollup.js:22463:24)
    at /Users/yairchu/dev/src/ProjectIt/packages/playground/node_modules/rollup/dist/shared/rollup.js:22426:26
```

**Comment by joswarmer** [comment]
You are right,  we moved the example languages to the samples folder, and now you first need to install a language in playground. For this you use `yarn install-example` just before `yarn example`.  I added this to the README.md.
